/**
 * English translation strings for NutriPadi.
 */
export const en = {
  // Common
  appName: "NutriPadi",
  tagline: "Your African Nutritionist",
  slogan: "Know your food. Eat smarter.",
  continue: "Continue",
  skip: "Skip",
  next: "Next",
  back: "Back",
  done: "Done",
  save: "Save",
  cancel: "Cancel",
  logout: "Log out",
  disclaimer:
    "NutriPadi gives food estimates and helpful tips. If you have a medical condition, please speak with a qualified health professional.",

  // Splash
  splashSubtitle: "Your African Nutritionist",

  // Onboarding
  onboarding1Title: "Meet Your Nutritionist",
  onboarding1Desc: "NutriPadi helps you understand African meals using smart food analysis.",
  onboarding2Title: "Scan, Learn, Improve",
  onboarding2Desc: "Take a photo of your meal and get nutrition insights instantly.",
  onboarding3Title: "Eat Better With Guidance",
  onboarding3Desc: "Get friendly tips based on your meals, goals, and eating habits.",
  onboardingHintTitle: "Next: Meet your Nutritionist",
  onboardingHintText: "After signup, NutriPadi will ask a few questions to personalize your food guidance.",

  // Language
  chooseLanguage: "Choose Your Language",
  chooseLanguageSub: "Select the language NutriPadi should use.",
  langEnglish: "English",
  langEnglishSub: "Continue in English",
  langYoruba: "Yorùbá",
  langYorubaSub: "Tẹsiwaju ni Yoruba",
  langHausa: "Hausa",
  langHausaSub: "Ci gaba da Hausa",
  langIgbo: "Igbo",
  langIgboSub: "Gaa n'ihu n'asụsụ Igbo",
  langSwahili: "Kiswahili",
  langSwahiliSub: "Endelea kwa Kiswahili",
  langFrench: "Français",
  langFrenchSub: "Continuer en français",
  langMoreSoon: "NutriPadi is structured for English, Yoruba, Hausa, and Igbo preference.",

  // Auth
  loginKicker: "Welcome back",
  loginTitle: "Let's check today's meals",
  loginSubtitle: "Log in to continue eating smarter.",
  signupKicker: "Welcome to NutriPadi",
  signupTitle: "Create your account",
  signupSubtitle: "Meet your food companion.",
  signupNote: "Nutrition setup comes next",
  signupNoteText: "NutriPadi will ask about your goals and food habits.",
  forgotPasswordTitle: "Forgot password?",
  forgotPasswordSubtitle: "We will send you a reset link.",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm password",
  fullName: "Full name",
  forgotPassword: "Forgot password?",
  noAccount: "Don't have an account? Sign up",
  hasAccount: "Already have an account? Log in",
  login: "Login",
  signUp: "Sign Up",

  // Setup
  setupEyebrow: "Nutrition Setup",
  step1Title: "Tell us about yourself",
  step1Subtitle: "These help NutriPadi give you better guidance.",
  step2Title: "What are your food goals?",
  step2Subtitle: "Pick all that apply, you can change these later.",
  step3Title: "What are your eating habits?",
  step3Subtitle: "Pick all that apply. This helps NutriPadi give useful advice.",
  step4Title: "Any health concerns?",
  step4Subtitle: "Pick all that apply, or choose none. This personalises your tips.",
  step5Title: "What should we call you?",
  step5Subtitle: "This keeps the app personal.",
  personalDetails: "Personal details",
  age: "Age",
  gender: "Gender",
  weight: "Weight (kg)",
  height: "Height (cm)",
  nickname: "Nickname",
  addPhotoLater: "Add photo later",
  changePhoto: "Change photo",
  finishSetup: "Finish Setup",
  locationLabel: "Where do you live?",
  locationPlaceholder: "e.g. Lagos, Nigeria",

  // Life stage (maternal focus)
  lifeStageTitle: "Who are we supporting?",
  lifeStageSubtitle: "NutriPadi tailors your nutrition targets and advice to your stage of life.",
  lifeStageGeneral: "Just me",
  lifeStageGeneralDesc: "Everyday nutrition tracking and healthier African meals.",
  lifeStagePregnant: "I'm pregnant",
  lifeStagePregnantDesc: "Protect you and your baby during pregnancy.",
  lifeStageNursing: "I'm a nursing mother",
  lifeStageNursingDesc: "Stay nourished while breastfeeding your baby (0–2 yrs).",
  lifeStageRequired: "Please choose one.",
  trimesterLabel: "Which trimester are you in?",
  trimesterFirst: "1st\nWeeks 1–12",
  trimesterSecond: "2nd\nWeeks 13–27",
  trimesterThird: "3rd\nWeeks 28–40",
  trimesterRequired: "Please select your trimester.",
  babyAgeLabel: "How old is your baby? (months)",
  babyAgePlaceholder: "e.g. 6",
  babyAgeRequired: "Please enter your baby's age in months.",
  maternalNote: "NutriPadi will watch your iron, folic acid, and protein closely, the nutrients that matter most for the first 1,000 days.",
  lifeStageLabel: "Life stage",

  // Goals
  goalEatHealthier: "Eat healthier",
  goalTrackCalories: "Track calories",
  goalManageWeight: "Manage weight",
  goalReduceCarbs: "Reduce excess carbs",
  goalUnderstandMeals: "Understand African meals",
  goalBetterHabits: "Build better food habits",
  goalMoreProtein: "Eat more protein",
  goalBoostEnergy: "Boost my energy",
  goalEatForBaby: "Eat well for my baby",
  goalEatForBabyDesc: "Pregnancy & nursing nutrition",
  goalsHint: "Pick all that apply.",

  // Eating lifestyle
  lifestyleSwallow: "I eat swallow often",
  lifestyleRice: "I eat rice often",
  lifestyleLateNight: "I eat late at night",
  lifestyleSnack: "I snack a lot",
  lifestylePortion: "I want to control how much I eat",
  lifestyleHealthier: "I want healthier African meals",
  lifestyleBigPortions: "I eat large portions",
  lifestyleSugaryDrinks: "I drink sugary drinks often",
  lifestyleLowProtein: "I rarely eat protein",
  lifestyleSkipMeals: "I often skip meals",
  lifestyleFastFood: "I eat fried or fast food often",
  lifestyleVeggies: "I rarely eat fruits or vegetables",
  lifestyleLowWater: "I don't drink enough water",
  lifestyleCravings: "I get strong food cravings",
  lifestyleAppetite: "My appetite changes a lot",
  lifestyleHint: "Pick all that apply.",

  // Health awareness
  healthGeneral: "General wellness",
  healthWeight: "Weight management",
  healthDiabetes: "Diabetes",
  healthHeart: "Heart health",
  healthBloodPressure: "Blood pressure",
  healthAnaemia: "Low iron / anaemia",
  healthGut: "Gut & digestion",
  healthPregnancy: "Pregnancy & baby nutrition",
  healthNone: "No specific concern",
  healthHint: "Pick all that apply, or choose none.",
  healthDisclaimer: "NutriPadi gives food estimates and tips. If you have a medical condition, please speak with a qualified health professional.",

  // Dashboard
  readyToEat: "Ready to eat smarter today?",
  aiReady: "Your AI Nutritionist is ready",
  aiReadyText: "I can help you scan meals, answer food questions, and track what you eat.",
  todayCalories: "Today's calories",
  ofDailyGoal: "of daily goal",
  waterReminder: "Water reminder",
  waterReminderText: "Had enough water today? Aim for at least 8 glasses.",
  quickActions: "Quick actions",
  scanMeal: "Scan Meal",
  askCoach: "Ask AI Coach",
  viewMealLog: "View Meal Log",
  browseFoods: "Browse Foods",
  aiInsightTitle: "Today's Tip",
  nutritionObs: "Food check",
  insightText: "You have logged more carb-heavy meals today. Try adding protein to your next meal.",
  recentMeals: "Recent meals",
  seeAll: "See all",
  dailyTip: "Daily tip",

  // Scan
  scanTitle: "Scan Your Meal",
  scanSubtitle: "Take a clear photo so your AI Nutritionist can understand your meal.",
  uploadImage: "Upload from Gallery",
  cameraNeeded: "Camera access needed",
  cameraNeededText: "Please allow camera access to scan foods.",
  grantPermission: "Grant Permission",

  // Analyzing
  analyzingTitle: "Your AI Nutritionist is thinking...",
  analyzingStep1: "Reading your food image...",
  analyzingStep2: "Identifying African dish...",
  analyzingStep3: "Checking how much food is on the plate...",
  analyzingStep4: "Checking food balance...",
  analyzingStep5: "Preparing your food advice...",

  // Food Result
  mealResult: "Meal Result",
  mealIdentified: "Meal identified",
  confidence: "confidence",
  estimatedCalories: "Estimated food energy",
  nutritionBreakdown: "What's in this food",
  aiNutritionistSays: "AI Nutritionist Says",
  betterPairing: "Better Pairing Suggestion",
  addToLog: "Add to Meal Log",
  askFollowUp: "Ask follow-up question",
  scanAgain: "Scan Again",
  estimateDisclaimer: "This is only an estimate. If you have a medical condition, please speak with a qualified health professional.",

  // AI Coach
  aiCoachTitle: "AI Nutritionist",
  aiCoachSub: "Ask about African food, wraps, plates, bowls, and balance",
  quickQuestions: "Quick questions",
  askAboutFood: "Ask about your food...",
  aiNutritionist: "AI Nutritionist",
  coachDisclaimer: "NutriPadi gives food estimates and general guidance. If you have a medical condition, please speak with a qualified health professional.",

  // Meal Log
  mealLogTitle: "Meal Log",
  mealLogSub: "Your AI Food Coach is monitoring your meals.",
  totalCalories: "Total calories",
  mealsLogged: "Meals logged",
  aiObservation: "AI Observation",
  viewWeeklyReport: "View Weekly Report",
  weeklyReportText: "See your food habits and summary.",
  breakfast: "Breakfast",
  lunch: "Lunch",
  dinner: "Dinner",
  snacks: "Snacks",

  // Profile
  profileTitle: "Profile",
  healthInfo: "Health information",
  nutritionGoal: "Food goal",
  eatingLifestyle: "Eating lifestyle",
  healthAwareness: "Health concerns",
  language: "Language",
  general: "General",
  settings: "Settings",
  daysStreak: "day streak",

  // Settings
  settingsTitle: "Settings",
  preferences: "Preferences",
  notifications: "Notifications",
  mealReminders: "Meal reminders",
  aiAdviceTone: "AI advice tone",
  darkMode: "Dark mode",
  measurementUnits: "Food amount labels",
  support: "Support",
  helpCenter: "Help center",
  privacyPolicy: "Privacy policy",
  aboutNutriPadi: "About NutriPadi",
  appVersion: "App version",
  account: "Account",
  deleteAccount: "Delete account",

  // Tone
  toneGentle: "Gentle",
  toneDirect: "Direct",
  toneMotivational: "Motivational",
  toneSimple: "Simple",

  // Tabs
  tabDashboard: "Dashboard",
  tabScan: "Scan Meal",
  tabCoach: "AI Coach",
  tabMealLog: "Meal Log",
  tabProfile: "Profile",

  // Smart Suggestions
  smartSuggestions: "Smart Suggestions",
  aiMealIdeas: "AI-powered meal ideas",
  adjustPortions: "These are simple meal ideas. Pick the amount that fits your goals.",

  // Nutrition Lessons
  nutritionLessons: "Food Lessons",
  learnFromAI: "Learn from your AI Food Coach",
  featuredTips: "Featured Tips",

  // Misc
  selected: "Selected",
  tapToChoose: "Tap to choose",
  meals: "meals",
  meal: "meal",
  kcal: "kcal",
};

export type TranslationKey = keyof typeof en;
