import { en } from "./en";
export const fr: typeof en = {
  ...en,
  appName: "NutriPadi", tagline: "Votre Nutritionniste IA", slogan: "Connaissez votre nourriture. Mangez mieux.",
  continue: "Continuer", skip: "Ignorer", next: "Suivant", back: "Retour", done: "Terminé", save: "Enregistrer", cancel: "Annuler", logout: "Déconnexion",
  disclaimer: "NutriPadi fournit des estimations nutritionnelles. Ne remplace pas un avis médical.",
  splashSubtitle: "Votre Nutritionniste IA",
  onboarding1Title: "Rencontrez votre Nutritionniste", onboarding1Desc: "NutriPadi vous aide à comprendre les repas africains.",
  addPhotoLater: "Ajouter une photo plus tard", changePhoto: "Changer la photo", finishSetup: "Terminer la configuration",
  locationLabel: "Où habitez-vous ?", locationPlaceholder: "ex. Dakar, Sénégal",
  chooseLanguage: "Choisissez votre langue", chooseLanguageSub: "Sélectionnez la langue que NutriPadi doit utiliser.", langMoreSoon: "D'autres langues seront bientôt disponibles.",
  loginKicker: "Bon retour", loginTitle: "Vérifions les repas d'aujourd'hui", loginSubtitle: "Connectez-vous pour continuer.",
  signupKicker: "Bienvenue sur NutriPadi", signupTitle: "Créez votre compte", signupSubtitle: "Rencontrez votre nutritionniste IA.",
  lifeStageTitle: "Qui accompagnons-nous ?", lifeStageSubtitle: "NutriPadi adapte vos objectifs nutritionnels à votre étape de vie.",
  lifeStageGeneral: "Juste moi", lifeStageGeneralDesc: "Suivi nutritionnel quotidien et repas africains plus sains.",
  lifeStagePregnant: "Je suis enceinte", lifeStagePregnantDesc: "Protégez-vous, vous et votre bébé, pendant la grossesse.",
  lifeStageNursing: "J'allaite mon bébé", lifeStageNursingDesc: "Restez bien nourrie pendant l'allaitement (0–2 ans).",
  trimesterLabel: "Dans quel trimestre êtes-vous ?", babyAgeLabel: "Quel âge a votre bébé ? (mois)",
  maternalNote: "NutriPadi surveillera de près votre fer, acide folique et protéines — essentiels pour les 1 000 premiers jours.",
};
