import { en } from "./en";
export const ha: typeof en = {
  ...en,
  appName: "NutriPadi", tagline: "Mai Ba da Shawarar Abinci", slogan: "San abincinka. Ci da hankali.",
  continue: "Ci gaba", skip: "Tsallake", next: "Na gaba", back: "Baya", done: "An gama", save: "Ajiye", cancel: "Soke", logout: "Fita",
  disclaimer: "NutriPadi yana ba da ƙiyasin abinci. Ba ya maye gurbin shawarar likita.",
  splashSubtitle: "Mai Ba da Shawarar Abinci",
  onboarding1Title: "Sadu da Mai Shawararka", onboarding1Desc: "NutriPadi yana taimaka ka fahimci abincin Najeriya.",
  onboarding2Title: "Duba, Koya, Inganta", onboarding2Desc: "Ɗauki hoton abincinka ka sami bayani nan take.",
  onboarding3Title: "Ci Abinci Mai Kyau", onboarding3Desc: "Sami shawarwari bisa abincinka da manufofinka.",
  onboardingHintTitle: "Na gaba: Sadu da mai shawararka", onboardingHintText: "Bayan rajista, za mu yi maka tambayoyi kaɗan.",
  chooseLanguage: "Zaɓi Harsheka", chooseLanguageSub: "Zaɓi harshen da NutriPadi zai yi amfani da shi.", langMoreSoon: "Ƙarin harsuna na zuwa nan gaba.",
  loginKicker: "Barka da dawowa", loginTitle: "Mu duba abincin yau", loginSubtitle: "Shiga don ci gaba.",
  signupKicker: "Barka da zuwa NutriPadi", signupTitle: "Ƙirƙiri asusunka", signupSubtitle: "Sadu da mai shawarar abincinka.",
  signupNote: "Saita na gaba", signupNoteText: "Mai shawararka zai tambaye ka game da manufofinka.",
  email: "Imel", password: "Kalmar sirri", confirmPassword: "Tabbatar da kalmar sirri", fullName: "Sunan cikakke",
  forgotPassword: "An manta kalmar sirri?", noAccount: "Ba ka da asusu? Yi rajista", hasAccount: "Kana da asusu? Shiga",
  login: "Shiga", signUp: "Yi Rajista",
  setupEyebrow: "Saita Mai Shawara",
  step1Title: "Gaya mana game da kanka", step1Subtitle: "Wannan yana taimaka wa NutriPadi.",
  step2Title: "Menene manufar abincinka?", step2Subtitle: "Zaɓi abin da ya fi muhimmanci.",
  step3Title: "Yaya kake cin abinci?", step3Subtitle: "Wannan yana taimaka wa mai shawararka.",
  step4Title: "Wani abu na musamman na lafiya?", step4Subtitle: "Wannan yana taimaka wajen keɓance shawarwari.",
  step5Title: "Me za mu kira ka?", step5Subtitle: "Don sanya app ɗin ya zama na kanka.",
  personalDetails: "Bayanai na sirri", age: "Shekaru", gender: "Jinsi",
  weight: "Nauyi (kg)", height: "Tsayi (cm)", nickname: "Sunan ladabi",
  addPhotoLater: "Ƙara hoto daga baya", finishSetup: "Gama Saita",
  goalEatHealthier: "Ci abinci mai kyau", goalTrackCalories: "Bi diddigin kalori", goalManageWeight: "Sarrafa nauyi",
  goalReduceCarbs: "Rage yawan carbs", goalUnderstandMeals: "Fahimci abincin Najeriya", goalBetterHabits: "Gina kyawawan al'adu",
  lifestyleSwallow: "Ina cin tuwo akai-akai", lifestyleRice: "Ina cin shinkafa akai-akai",
  lifestyleLateNight: "Ina cin abinci da dare", lifestyleSnack: "Ina cin kayan ciki da yawa",
  lifestylePortion: "Ina son sarrafa girma", lifestyleHealthier: "Ina son abinci mai kyau",
  healthGeneral: "Lafiya gaba ɗaya", healthWeight: "Sarrafa nauyi", healthDiabetes: "Sanin ciwon sukari",
  healthHeart: "Sanin lafiyar zuciya", healthNone: "Babu na musamman",
  healthDisclaimer: "NutriPadi yana ba da ƙiyasin abinci. Ba ya maye gurbin likita.",
  readyToEat: "Ka shirya cin abinci mai kyau?", aiReady: "Mai shawararka ya shirya",
  aiReadyText: "Zan iya taimaka maka.", todayCalories: "Kalorin yau", ofDailyGoal: "na manufar yau",
  waterReminder: "Tunatarwar ruwa", waterReminderText: "Ka sha isasshen ruwa yau?",
  quickActions: "Ayyuka masu sauri", scanMeal: "Duba Abinci", askCoach: "Tambayi", viewMealLog: "Duba Rikodin",
  browseFoods: "Bincika Abinci", aiInsightTitle: "Shawarar Yau", nutritionObs: "Lura",
  insightText: "Ka ci abinci mai yawan carbs yau. Gwada ƙara furotin.", recentMeals: "Abincin baya-bayan nan", seeAll: "Duba duka", dailyTip: "Shawara",
  scanTitle: "Duba Abincinka", scanSubtitle: "Ɗauki hoto mai kyau.", uploadImage: "Ɗora hoto",
  cameraNeeded: "Ana buƙatar kyamara", cameraNeededText: "Da fatan za a ba da damar kyamara.", grantPermission: "Ba da Dama",
  analyzingTitle: "Mai shawararka yana tunani...", analyzingStep1: "Yana karanta hoton...", analyzingStep2: "Yana gano abincin...",
  analyzingStep3: "Yana ƙiyasta girma...", analyzingStep4: "Yana bincike...", analyzingStep5: "Yana shirya shawara...",
  mealResult: "Sakamakon Abinci", mealIdentified: "An gano abinci", confidence: "tabbaci",
  estimatedCalories: "Ƙiyasin kalori", nutritionBreakdown: "Bayani",
  aiNutritionistSays: "Mai shawara ya ce", betterPairing: "Shawarar Mafi Kyau",
  addToLog: "Ƙara zuwa Rikodin", askFollowUp: "Yi wata tambaya", scanAgain: "Sake Duba",
  estimateDisclaimer: "Waɗannan ƙiyasi ne. Ba su maye gurbin shawarar likita ba.",
  aiCoachTitle: "Mai Shawara", aiCoachSub: "Tambaya game da abinci", quickQuestions: "Tambayoyi masu sauri",
  askAboutFood: "Tambayi game da abincinka...", aiNutritionist: "Mai Shawarar Abinci",
  coachDisclaimer: "Ba ya maye gurbin shawarar likita.",
  mealLogTitle: "Rikodin Abinci", mealLogSub: "Mai shawararka yana lura.",
  totalCalories: "Jimlar kalori", mealsLogged: "Abincin da aka yi rikodin", aiObservation: "Lura",
  viewWeeklyReport: "Duba Rahoton Mako", weeklyReportText: "Duba salon abincinka.",
  breakfast: "Karin kumallo", lunch: "Abincin rana", dinner: "Abincin dare", snacks: "Kayan ciki",
  profileTitle: "Bayani", healthInfo: "Bayanan lafiya", nutritionGoal: "Manufa",
  eatingLifestyle: "Salon cin abinci", healthAwareness: "Sanin lafiya", language: "Harshe",
  general: "Gabaɗaya", settings: "Saiti", daysStreak: "kwanakin jere",
  settingsTitle: "Saiti", preferences: "Zaɓuɓɓuka", notifications: "Sanarwa",
  mealReminders: "Tunatarwar abinci", aiAdviceTone: "Salon shawara", darkMode: "Yanayin duhu",
  measurementUnits: "Ma'auni", support: "Tallafi", helpCenter: "Taimako",
  privacyPolicy: "Manufar sirri", aboutNutriPadi: "Game da NutriPadi", appVersion: "Sigar app",
  account: "Asusu", deleteAccount: "Share asusu",
  toneGentle: "A hankali", toneDirect: "Kai tsaye", toneMotivational: "Mai ƙarfafawa", toneSimple: "Sauƙi",
  tabDashboard: "Gida", tabScan: "Duba", tabCoach: "Shawara", tabMealLog: "Rikodin", tabProfile: "Bayani",
  smartSuggestions: "Shawarwari", aiMealIdeas: "Ra'ayoyin abinci", adjustPortions: "Daidaita girman abinci.",
  nutritionLessons: "Darussan Abinci", learnFromAI: "Koya daga mai shawara", featuredTips: "Shawarwari na Musamman",
  foodDatabase: "Tarin Abinci", searchFoods: "Bincika abinci...", bestFor: "Mafi kyau don", watchOutFor: "Yi hankali da", aiTip: "Shawara",
  selected: "An zaɓa", tapToChoose: "Taɓa don zaɓa", meals: "abinci", meal: "abinci", kcal: "kcal",
  forgotPasswordTitle: "An manta kalmar sirri?", forgotPasswordSubtitle: "Za mu aika maka hanyar sake saita.",
};
