import { en } from "./en";
export const ig: typeof en = {
  ...en,
  appName: "NutriPadi", tagline: "Onye Ndụmọdụ Nri gị", slogan: "Mara nri gị. Rie nke ọma.",
  continue: "Gaa n'ihu", skip: "Wụfee", next: "Ọzọ", back: "Laghachi", done: "Emechara", save: "Chekwaa", cancel: "Kagbuo", logout: "Pụọ",
  disclaimer: "NutriPadi na-enye nkọwa nri. Ọ bụghị ọgwụgwọ dọkịta.",
  splashSubtitle: "Onye Ndụmọdụ Nri gị",
  onboarding1Title: "Hụ Onye Ndụmọdụ Gị", onboarding1Desc: "NutriPadi na-enyere gị aka ịghọta nri Africa.",
  onboarding2Title: "Nyocha, Mụta, Mezie", onboarding2Desc: "See foto nri gị wee nweta ọmụma ozugbo.",
  onboarding3Title: "Rie Nke Ọma", onboarding3Desc: "Nweta ndụmọdụ dabere na nri gị na ebumnuche gị.",
  onboardingHintTitle: "Ọzọ: Hụ onye ndụmọdụ gị", onboardingHintText: "Mgbe ị debanyere aha, anyị ga-ajụ ajụjụ ole na ole.",
  chooseLanguage: "Họrọ Asụsụ Gị", chooseLanguageSub: "Họrọ asụsụ NutriPadi ga-eji.", langMoreSoon: "Ọtụtụ asụsụ na-abịa n'oge na-adịghị anya.",
  loginKicker: "Nnọọ", loginTitle: "Ka anyị lee nri taa", loginSubtitle: "Banye iji gaa n'ihu.",
  signupKicker: "Nnọọ na NutriPadi", signupTitle: "Mepụta akaụntụ gị", signupSubtitle: "Hụ onye ndụmọdụ nri gị.",
  signupNote: "Nhazi na-esote", signupNoteText: "Onye ndụmọdụ gị ga-ajụ gbasara ebumnuche gị.",
  email: "Ozi-e", password: "Okwuntụghe", confirmPassword: "Kwenye okwuntụghe", fullName: "Aha zuru oke",
  forgotPassword: "Chefuru okwuntụghe?", noAccount: "Enweghị akaụntụ? Debanye aha", hasAccount: "Nwere akaụntụ? Banye",
  login: "Banye", signUp: "Debanye Aha",
  setupEyebrow: "Nhazi Ndụmọdụ",
  step1Title: "Gwa anyị maka onwe gị", step1Subtitle: "Nke a na-enyere NutriPadi aka.",
  step2Title: "Gịnị bụ ebumnuche gị?", step2Subtitle: "Họrọ nke kacha mkpa.",
  step3Title: "Kedu ka ị si eri nri?", step3Subtitle: "Nke a na-enyere onye ndụmọdụ gị aka.",
  step4Title: "Enwere mmasị ahụike pụrụ iche?", step4Subtitle: "Nke a na-enyere aka ịhazi ndụmọdụ gị.",
  step5Title: "Gịnị ka anyị ga-akpọ gị?", step5Subtitle: "Ka ngwa ahụ dị onwe gị.",
  personalDetails: "Nkọwa onwe gị", age: "Afọ", gender: "Oke/nwanyị",
  weight: "Arọ (kg)", height: "Elu (cm)", nickname: "Aha",
  addPhotoLater: "Tinye foto mgbe e mesịrị", changePhoto: "Gbanwee foto", finishSetup: "Mechaa Nhazi",
  goalEatHealthier: "Rie nke ọma karịa", goalTrackCalories: "Soro ụzọ kalori", goalManageWeight: "Jikwaa arọ",
  goalReduceCarbs: "Belata carbs", goalUnderstandMeals: "Ghọta nri Africa", goalBetterHabits: "Wuo àgwà iri nri ọma",
  lifestyleSwallow: "Ana m eri swallow mgbe niile", lifestyleRice: "Ana m eri rice mgbe niile",
  lifestyleLateNight: "Ana m eri nri n'abalị", lifestyleSnack: "Ana m ata ọtụtụ snack",
  lifestylePortion: "Achọrọ m ijikwa oke nri", lifestyleHealthier: "Achọrọ m nri Africa ka mma",
  healthGeneral: "Ahụike n'ozuzu", healthWeight: "Njikwa arọ", healthDiabetes: "Ịmata maka ọrịa shuga",
  healthHeart: "Ịmata maka ahụike obi", healthNone: "Enweghị nke pụrụ iche",
  healthDisclaimer: "NutriPadi na-enye nkọwa nri. Ọ bụghị ọgwụgwọ dọkịta.",
  readyToEat: "Ị dị njikere iri nke ọma taa?", aiReady: "Onye ndụmọdụ gị dị njikere",
  aiReadyText: "M nwere ike inyere gị aka.", todayCalories: "Kalori taa", ofDailyGoal: "nke ebumnuche",
  waterReminder: "Ncheta mmiri", waterReminderText: "Ị ṅụọla mmiri zuru taa?",
  quickActions: "Ihe ngwa ngwa", scanMeal: "Nyocha Nri", askCoach: "Jụọ", viewMealLog: "Lee Ndekọ",
  browseFoods: "Chọọ Nri", aiInsightTitle: "Ndụmọdụ Taa", nutritionObs: "Nlele",
  insightText: "Ị riela ọtụtụ carbs taa. Gbalịa ịtinye protein.", recentMeals: "Nri oge na-adịbeghị anya", seeAll: "Lee niile", dailyTip: "Ndụmọdụ",
  scanTitle: "Nyocha Nri Gị", scanSubtitle: "See foto doro anya.", uploadImage: "Bulite foto",
  cameraNeeded: "Achọrọ ikike kamera", cameraNeededText: "Biko nye ikike kamera.", grantPermission: "Nye Ikike",
  analyzingTitle: "Onye ndụmọdụ gị na-eche echiche...", analyzingStep1: "Na-agụ foto...", analyzingStep2: "Na-achọpụta nri...",
  analyzingStep3: "Na-atụle oke...", analyzingStep4: "Na-enyocha...", analyzingStep5: "Na-akwadebe ndụmọdụ...",
  mealResult: "Nsonaazụ Nri", mealIdentified: "Achọpụtara nri", confidence: "ntụkwasị obi",
  estimatedCalories: "Nkọwa kalori", nutritionBreakdown: "Nkọwa nri",
  aiNutritionistSays: "Onye ndụmọdụ kwuru", betterPairing: "Atụmatụ Ka Mma",
  addToLog: "Tinye na Ndekọ", askFollowUp: "Jụọ ajụjụ ọzọ", scanAgain: "Nyocha Ọzọ",
  estimateDisclaimer: "Ndị a bụ nkọwa. Ha abụghị ọgwụgwọ dọkịta.",
  aiCoachTitle: "Onye Ndụmọdụ", aiCoachSub: "Jụọ ihe ọ bụla maka nri", quickQuestions: "Ajụjụ ngwa ngwa",
  askAboutFood: "Jụọ maka nri gị...", aiNutritionist: "Onye Ndụmọdụ Nri",
  coachDisclaimer: "Ọ bụghị ọgwụgwọ dọkịta.",
  mealLogTitle: "Ndekọ Nri", mealLogSub: "Onye ndụmọdụ gị na-elele.",
  totalCalories: "Nkwurịta kalori", mealsLogged: "Nri e dekọrọ", aiObservation: "Nlele",
  viewWeeklyReport: "Lee Akụkọ Izu", weeklyReportText: "Lee usoro nri gị.",
  breakfast: "Nri ụtụtụ", lunch: "Nri ehihie", dinner: "Nri anyasị", snacks: "Snack",
  profileTitle: "Profaịlụ", healthInfo: "Ozi ahụike", nutritionGoal: "Ebumnuche",
  eatingLifestyle: "Ụdị nri ị na-eri", healthAwareness: "Ịmata ahụike", language: "Asụsụ",
  general: "N'ozuzu", settings: "Ntọala", daysStreak: "ụbọchị n'usoro",
  settingsTitle: "Ntọala", preferences: "Nhọrọ", notifications: "Ọkwa",
  mealReminders: "Ncheta nri", aiAdviceTone: "Ụdị ndụmọdụ", darkMode: "Ọchịchịrị",
  measurementUnits: "Nha", support: "Nkwado", helpCenter: "Enyemaka",
  privacyPolicy: "Iwu nzuzo", aboutNutriPadi: "Maka NutriPadi", appVersion: "Ụdị ngwa",
  account: "Akaụntụ", deleteAccount: "Hichapụ akaụntụ",
  toneGentle: "Nwayọọ", toneDirect: "Kpọmkwem", toneMotivational: "Nkwado", toneSimple: "Mfe",
  tabDashboard: "Ụlọ", tabScan: "Nyocha", tabCoach: "Ndụmọdụ", tabMealLog: "Ndekọ", tabProfile: "Profaịlụ",
  smartSuggestions: "Atụmatụ", aiMealIdeas: "Echiche nri", adjustPortions: "Hazie oke nri gị.",
  nutritionLessons: "Ihe Ọmụmụ Nri", learnFromAI: "Mụta n'aka onye ndụmọdụ", featuredTips: "Ndụmọdụ Pụrụ Iche",
  selected: "Ahọpụtara", tapToChoose: "Pịa ịhọrọ", meals: "nri", meal: "nri", kcal: "kcal",
  forgotPasswordTitle: "Chefuru okwuntụghe?", forgotPasswordSubtitle: "Anyị ga-ezitere gị njikọ.",
  lifeStageTitle: "Onye ka anyị na-enyere aka?", lifeStageSubtitle: "NutriPadi na-ahazi ihe mgbaru ọsọ nri gị dabere na ọkwa ndụ gị.",
  lifeStageGeneral: "Naanị m", lifeStageGeneralDesc: "Nlekọta nri kwa ụbọchị na nri Afrika ka mma.",
  lifeStagePregnant: "Adị m ime", lifeStagePregnantDesc: "Chebe gị na nwa gị n'oge ịdị ime.",
  lifeStageNursing: "Ana m enye nwa ara", lifeStageNursingDesc: "Nweta nri zuru oke mgbe ị na-enye nwa ara (afọ 0–2).",
  trimesterLabel: "Ị nọ n'ọnọdụ ọmụmụ nke ole?", babyAgeLabel: "Nwa gị dị afọ ole? (ọnwa)",
  maternalNote: "NutriPadi ga-elebara ígwè, folic acid, na protein gị anya — ndị kacha mkpa maka ụbọchị 1,000 mbụ.",
};
