import { en } from "./en";
export const sw: typeof en = {
  ...en,
  appName: "NutriPadi", tagline: "Mshauri wako wa Lishe", slogan: "Jua chakula chako. Kula vizuri.",
  continue: "Endelea", skip: "Ruka", next: "Ifuatayo", back: "Nyuma", done: "Tayari", save: "Hifadhi", cancel: "Ghairi", logout: "Ondoka",
  disclaimer: "NutriPadi inatoa makadirio ya lishe. Sio mbadala wa ushauri wa daktari.",
  splashSubtitle: "Mshauri wako wa Lishe",
  onboarding1Title: "Kutana na Mshauri Wako", onboarding1Desc: "NutriPadi inakusaidia kuelewa vyakula vya Afrika.",
  addPhotoLater: "Ongeza picha baadaye", changePhoto: "Badilisha picha", finishSetup: "Maliza Usanidi",
  locationLabel: "Unaishi wapi?", locationPlaceholder: "mfano Nairobi, Kenya",
  chooseLanguage: "Chagua Lugha Yako", chooseLanguageSub: "Chagua lugha ambayo NutriPadi itatumia.", langMoreSoon: "Lugha zaidi zinakuja hivi karibuni.",
  loginKicker: "Karibu tena", loginTitle: "Tuangalie milo ya leo", loginSubtitle: "Ingia ili uendelee.",
  signupKicker: "Karibu kwenye NutriPadi", signupTitle: "Fungua akaunti yako", signupSubtitle: "Kutana na mshauri wako wa lishe.",
  lifeStageTitle: "Tunamsaidia nani?", lifeStageSubtitle: "NutriPadi hurekebisha malengo yako ya lishe kulingana na hatua yako ya maisha.",
  lifeStageGeneral: "Mimi tu", lifeStageGeneralDesc: "Ufuatiliaji wa lishe wa kila siku na milo bora ya Kiafrika.",
  lifeStagePregnant: "Nina mimba", lifeStagePregnantDesc: "Jilinde wewe na mtoto wako wakati wa ujauzito.",
  lifeStageNursing: "Mama ananyonyesha", lifeStageNursingDesc: "Endelea kupata lishe bora unaponyonyesha (miaka 0–2).",
  trimesterLabel: "Uko katika robo gani ya ujauzito?", babyAgeLabel: "Mtoto wako ana umri gani? (miezi)",
  maternalNote: "NutriPadi itafuatilia kwa karibu madini ya chuma, asidi ya foliki na protini — muhimu kwa siku 1,000 za kwanza.",
};
