import { en } from "./en";
export const yo: typeof en = {
  ...en,
  appName: "NutriPadi", tagline: "Olùrànlọ́wọ́ Oúnjẹ rẹ", slogan: "Mọ oúnjẹ rẹ. Jẹun dáadáa.",
  continue: "Tẹsiwaju", skip: "Fo", next: "Ẹ̀yìn", back: "Padà", done: "Pari", save: "Fi pamọ́", cancel: "Fagilee", logout: "Jade",
  disclaimer: "NutriPadi ń fúnni ní ìṣirò oúnjẹ. Kì í ṣe aṣàyẹ̀wò dókítà.",
  splashSubtitle: "Olùrànlọ́wọ́ Oúnjẹ rẹ",
  onboarding1Title: "Pàdé Olùrànlọ́wọ́ Rẹ", onboarding1Desc: "NutriPadi ń ràn ọ́ lọ́wọ́ láti mọ oúnjẹ Áfíríkà.",
  onboarding2Title: "Ṣàwárí, Kọ́, Dára Sí i", onboarding2Desc: "Ya àwòrán oúnjẹ rẹ, gba ìmọ̀ràn lẹ́sẹ̀kẹsẹ̀.",
  onboarding3Title: "Jẹun Dáadáa", onboarding3Desc: "Gba àwọn ìmọ̀ràn tó dá lórí àwọn àfojúsùn rẹ.",
  onboardingHintTitle: "Ẹ̀yìn: Pàdé olùrànlọ́wọ́ rẹ", onboardingHintText: "Lẹ́yìn ìforúkọsílẹ̀, a ó béèrè àwọn ìbéèrè díẹ̀.",
  chooseLanguage: "Yan Èdè Rẹ", chooseLanguageSub: "Yan èdè tí NutriPadi yóò lò.", langMoreSoon: "Àwọn èdè mìíràn ń bọ̀.",
  loginKicker: "Ẹ káàbọ̀", loginTitle: "Jẹ́ ká wo oúnjẹ lónìí", loginSubtitle: "Wọlé láti tẹ̀síwájú.",
  signupKicker: "Ẹ káàbọ̀ sí NutriPadi", signupTitle: "Ṣẹ̀dá àkọọ́lẹ̀ rẹ", signupSubtitle: "Pàdé olùrànlọ́wọ́ oúnjẹ rẹ.",
  signupNote: "Ìṣètò ń bọ̀", signupNoteText: "Olùrànlọ́wọ́ yóò béèrè nípa àfojúsùn rẹ.",
  email: "Ímeèlì", password: "Ọ̀rọ̀ aṣínà", confirmPassword: "Ṣe àfidájú ọ̀rọ̀ aṣínà", fullName: "Orúkọ kíkún",
  forgotPassword: "Gbàgbé ọ̀rọ̀ aṣínà?", noAccount: "Ò ní àkọọ́lẹ̀? Forúkọsílẹ̀", hasAccount: "Ní àkọọ́lẹ̀? Wọlé",
  login: "Wọlé", signUp: "Forúkọsílẹ̀",
  setupEyebrow: "Ìṣètò Olùrànlọ́wọ́",
  step1Title: "Sọ fún wa nípa rẹ", step1Subtitle: "Èyí ń ràn NutriPadi lọ́wọ́.",
  step2Title: "Kí ni àfojúsùn rẹ?", step2Subtitle: "Yan ohun tó ṣe pàtàkì jù.",
  step3Title: "Báwo ni o ṣe ń jẹun?", step3Subtitle: "Èyí ń ràn olùrànlọ́wọ́ rẹ lọ́wọ́.",
  step4Title: "Ǹjẹ́ o ní ìmọ̀ ìlera pàtó?", step4Subtitle: "Èyí ń ṣe àdàni ìmọ̀ràn rẹ.",
  step5Title: "Kí la ó pè ẹ́?", step5Subtitle: "Kí ètò náà jẹ́ ti ara ẹni.",
  personalDetails: "Àlàyé ara ẹni", age: "Ọjọ́ orí", gender: "Akọ tàbí abo",
  weight: "Ìwúwo (kg)", height: "Gíga (cm)", nickname: "Orúkọ àdàni",
  addPhotoLater: "Fi àwòrán kùn lẹ́yìn", finishSetup: "Parí Ìṣètò",
  goalEatHealthier: "Jẹun dáadáa", goalTrackCalories: "Ṣàmójútó kalori", goalManageWeight: "Ṣàkóso ìwúwo",
  goalReduceCarbs: "Dín carbs kù", goalUnderstandMeals: "Mọ oúnjẹ Áfíríkà", goalBetterHabits: "Kọ́ àṣà tó dára",
  lifestyleSwallow: "Mo máa ń jẹ swallow", lifestyleRice: "Mo máa ń jẹ ìrẹsì",
  lifestyleLateNight: "Mo máa ń jẹun lálẹ́", lifestyleSnack: "Mo máa ń jẹ snack púpọ̀",
  lifestylePortion: "Mo fẹ́ ṣàkóso ìwọ̀n", lifestyleHealthier: "Mo fẹ́ oúnjẹ tó dára sí i",
  healthGeneral: "Ìlera gbogbogbò", healthWeight: "Ìṣàkóso ìwúwo", healthDiabetes: "Ìmọ̀ àrùn ṣúgà",
  healthHeart: "Ìmọ̀ ìlera ọkàn", healthNone: "Kò sí pàtó",
  healthDisclaimer: "NutriPadi ń fúnni ní ìṣirò oúnjẹ. Kì í ṣe aṣàyẹ̀wò dókítà.",
  readyToEat: "Ṣé o ti ṣetán jẹun dáadáa?", aiReady: "Olùrànlọ́wọ́ rẹ ti ṣetán",
  aiReadyText: "Mo lè ràn ọ́ lọ́wọ́.", todayCalories: "Kalori ọjọ́ yìí", ofDailyGoal: "ti àfojúsùn",
  waterReminder: "Ìrántí omi", waterReminderText: "Ṣé o ti mu omi tó lónìí?",
  quickActions: "Ìgbésẹ̀ kíákíá", scanMeal: "Ṣàwárí Oúnjẹ", askCoach: "Béèrè", viewMealLog: "Wo Àkọsílẹ̀",
  browseFoods: "Wá Oúnjẹ", aiInsightTitle: "Ìmọ̀ràn Ọjọ́ Yìí", nutritionObs: "Àkíyèsí",
  insightText: "O ti jẹ carbs púpọ̀ lónìí. Fi protein kùn.", recentMeals: "Oúnjẹ àìpẹ́", seeAll: "Wo gbogbo", dailyTip: "Ìmọ̀ràn",
  scanTitle: "Ṣàwárí Oúnjẹ Rẹ", scanSubtitle: "Ya àwòrán tó ṣe kedere.", uploadImage: "Gbe àwòrán sókè",
  cameraNeeded: "A nílò kámẹ́rà", cameraNeededText: "Jọ̀wọ́ fún ní ààyè.", grantPermission: "Fún Ní Ààyè",
  analyzingTitle: "Olùrànlọ́wọ́ ń ronú...", analyzingStep1: "Ń ka àwòrán...", analyzingStep2: "Ń dámọ̀ oúnjẹ...",
  analyzingStep3: "Ń ṣirò ìwọ̀n...", analyzingStep4: "Ń ṣàyẹ̀wò...", analyzingStep5: "Ń pèsè ìmọ̀ràn...",
  mealResult: "Èsì Oúnjẹ", mealIdentified: "A ti dámọ̀", confidence: "ìgbàgbọ́",
  estimatedCalories: "Iye kalori", nutritionBreakdown: "Àlàyé oúnjẹ",
  aiNutritionistSays: "Olùrànlọ́wọ́ sọ pé", betterPairing: "Ìmọ̀ràn Tó Dára",
  addToLog: "Fi Kùn Àkọsílẹ̀", askFollowUp: "Béèrè ìbéèrè mìíràn", scanAgain: "Ṣàwárí Lẹ́ẹ̀kansi",
  estimateDisclaimer: "Àwọn iye yìí jẹ́ ìṣirò. Kì í ṣe àyẹ̀wò dókítà.",
  aiCoachTitle: "Olùrànlọ́wọ́", aiCoachSub: "Béèrè nípa oúnjẹ", quickQuestions: "Ìbéèrè kíákíá",
  askAboutFood: "Béèrè nípa oúnjẹ rẹ...", aiNutritionist: "Olùrànlọ́wọ́ Oúnjẹ",
  coachDisclaimer: "Kì í rọ́pò ìmọ̀ràn dókítà.",
  mealLogTitle: "Àkọsílẹ̀ Oúnjẹ", mealLogSub: "Olùrànlọ́wọ́ ń ṣe àmójútó.",
  totalCalories: "Àpapọ̀ kalori", mealsLogged: "Oúnjẹ tí a kọ sílẹ̀", aiObservation: "Àkíyèsí",
  viewWeeklyReport: "Wo Ìròyìn Ọ̀sẹ̀", weeklyReportText: "Wo àwọn àṣà rẹ.",
  breakfast: "Àárọ̀", lunch: "Ọ̀sán", dinner: "Alẹ́", snacks: "Snack",
  profileTitle: "Profaili", healthInfo: "Àlàyé ìlera", nutritionGoal: "Àfojúsùn",
  eatingLifestyle: "Àṣà jíjẹun", healthAwareness: "Ìmọ̀ ìlera", language: "Èdè",
  general: "Gbogbogbò", settings: "Ètò", daysStreak: "ọjọ́ lẹ́sẹẹsẹ",
  settingsTitle: "Ètò", preferences: "Àṣàyàn", notifications: "Ìfitónilétí",
  mealReminders: "Ìrántí oúnjẹ", aiAdviceTone: "Ohùn ìmọ̀ràn", darkMode: "Ìrísí dúdú",
  measurementUnits: "Ìwọ̀n", support: "Àtìlẹ́yìn", helpCenter: "Ìrànlọ́wọ́",
  privacyPolicy: "Àṣírí", aboutNutriPadi: "Nípa NutriPadi", appVersion: "Ẹ̀yà ètò",
  account: "Àkọọ́lẹ̀", deleteAccount: "Pa àkọọ́lẹ̀",
  toneGentle: "Pẹ̀lẹ́", toneDirect: "Tàrà", toneMotivational: "Ìrúni", toneSimple: "Rọrùn",
  tabDashboard: "Ilé", tabScan: "Ṣàwárí", tabCoach: "Olùrànlọ́wọ́", tabMealLog: "Àkọsílẹ̀", tabProfile: "Profaili",
  smartSuggestions: "Ìmọ̀ràn", aiMealIdeas: "Èrò oúnjẹ", adjustPortions: "Ṣàtúnṣe ìwọ̀n rẹ.",
  nutritionLessons: "Ẹ̀kọ́ Oúnjẹ", learnFromAI: "Kọ́ lọ́wọ́ olùrànlọ́wọ́", featuredTips: "Ìmọ̀ràn Pàtàkì",
  selected: "A ti yàn", tapToChoose: "Tẹ láti yan", meals: "oúnjẹ", meal: "oúnjẹ", kcal: "kcal",
  forgotPasswordTitle: "Gbàgbé ọ̀rọ̀ aṣínà?", forgotPasswordSubtitle: "A ó fi ọ̀nà ránṣẹ́.",
};
